# Generated by Django 2.1.4 on 2020-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='content',
            field=models.CharField(default='abc', max_length=200, verbose_name='正文'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='summary',
            field=models.CharField(default='abc', max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='ziyu',
            name='content',
            field=models.CharField(blank=True, max_length=2000, verbose_name='正文'),
        ),
    ]
