# Generated by Django 2.1.4 on 2020-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200109_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=models.CharField(max_length=200, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
